/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lensico_inventory.pos;

import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author Airi
 */
public class LOADING_SCREEN extends javax.swing.JFrame {

   public JProgressBar progressbar;
   public JLabel pleasewait;
    
    
    public LOADING_SCREEN() {
        initComponents();
        progressbar = new JProgressBar();
        pleasewait = new JLabel();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        pleaseWait = new javax.swing.JLabel();
        loadingscreen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 100, 1215, 838));
        setName("LOADING"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1215, 838));
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(1215, 838));
        jPanel1.setLayout(null);

        progressBar.setBackground(new java.awt.Color(255, 255, 255));
        progressBar.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        progressBar.setForeground(new java.awt.Color(102, 255, 102));
        progressBar.setBorder(null);
        progressBar.setStringPainted(true);
        jPanel1.add(progressBar);
        progressBar.setBounds(80, 718, 1040, 30);

        pleaseWait.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pleaseWait.setForeground(new java.awt.Color(255, 255, 255));
        pleaseWait.setText("Please wait...");
        jPanel1.add(pleaseWait);
        pleaseWait.setBounds(90, 680, 380, 40);

        loadingscreen.setBackground(new java.awt.Color(255, 255, 255));
        loadingscreen.setForeground(new java.awt.Color(178, 50, 50));
        loadingscreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesss_panel/LOADING SCREEN.png"))); // NOI18N
        jPanel1.add(loadingscreen);
        loadingscreen.setBounds(0, 0, 1200, 800);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOADING_SCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOADING_SCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOADING_SCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOADING_SCREEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOADING_SCREEN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel loadingscreen;
    public static javax.swing.JLabel pleaseWait;
    public static javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
